# Generated by Django 3.1 on 2020-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
