# Generated by Django 3.1 on 2020-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_auto_20200824_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
